### ISSUE TITLE
Install on / (root) only?

### ISSUE THREAD

**Issue by bzg** [YunoHost-Apps/codimd_ynh#5]
Hi, thanks *a lot* for packaging codimd, I'd love to use it on ynh.

I tried to install it but it seems to require root installation, preventing other applications to be installed.

Is this a hard limitation? Any wait to circumvent it?

Thanks!

**Comment by alexAubin** [comment]
According to https://github.com/codimd/server/blob/master/docs/configuration-config-file.md there's a `urlPath` setting for this, tried to implement it during my commit a few minutes ago, and it only half-worked because it wasnt taken into account for the static files ... So for now yea, have to live with this.

(Still, be careful anyway with this app, it's not to be considered as stable)

**Comment by bzg** [comment]
Okay, thanks!
